# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-kubectl-apply
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-kubectl-apply
    source:
      repo: https://github.com/singhalbhaskar/terraform-google-kubectl-apply.git
      sourceType: git
    version: 0.0.2
    actuationTool:
      flavor: Terraform
      version: ">= 1.3"
    description:
      tagline: This is an auto-generated module.
      detailed: "This module was generated from "
      preDeploy: To deploy this blueprint you must have an active billing account and billing permissions.
    icon: assets/icon.png
    costEstimate:
      description: Blueprint cost details
      url: https://cloud.google.com/products/calculator?id=02fb0c45-cc29-4567-8cc6-f72ac9024add
  content:
    architecture:
      diagramUrl: https://www.link-to-architecture-diagram.com
      description:
        - 1. Architecture description step no. 1
        - 2. Architecture description step no. 2
        - 3. Architecture description step no. N
    documentation:
      - title: Hosting a Static Website
        url: https://cloud.google.com/storage/docs/hosting-static-website
    examples:
      - name: simple_example
        location: examples/simple_example
  interfaces:
    variables:
      - name: project_id
        description: The project ID that hosts the gke cluster.
        varType: string
        required: true
      - name: cluster_id
        description: An identifier for the gke cluster resource with format projects/<project_id>/locations/<region>/clusters/<name>.
        varType: string
        required: true
        connections:
          - source:
              source: github.com/singhalbhaskar/terraform-google-gke-cluster
              version: ">= 0.0.1"
            spec:
              outputExpr: cluster_id
      - name: apply_manifests
        description: A list of manifests to apply to GKE cluster using kubectl. For more details see [kubectl module's inputs](kubectl/README.md).
        varType: |-
          list(object({
              content           = optional(string, null)
              source            = optional(string, null)
              template_vars     = optional(map(any), null)
              server_side_apply = optional(bool, false)
              wait_for_rollout  = optional(bool, true)
            }))
        defaultValue: []
      - name: kueue
        description: Install and configure [Kueue](https://kueue.sigs.k8s.io/docs/overview/) workload scheduler. A configuration yaml/template file can be provided with config_path to be applied right after kueue installation. If a template file provided, its variables can be set to config_template_vars.
        varType: |-
          object({
              install              = optional(bool, false)
              version              = optional(string, "v0.8.1")
              config_path          = optional(string, null)
              config_template_vars = optional(map(any), null)
            })
        defaultValue: {}
      - name: jobset
        description: Install [Jobset](https://github.com/kubernetes-sigs/jobset) which manages a group of K8s [jobs](https://kubernetes.io/docs/concepts/workloads/controllers/job/) as a unit.
        varType: |-
          object({
              install = optional(bool, false)
              version = optional(string, "v0.5.2")
            })
        defaultValue: {}
      - name: additional_networks
        description: Additional network interface details for GKE, if any. Providing additional networks enables multi networking and creates relevat network objects on the cluster.
        varType: |-
          list(object({
              network            = string
              subnetwork         = string
              subnetwork_project = string
              network_ip         = string
              nic_type           = string
              stack_type         = string
              queue_count        = number
              access_config = list(object({
                nat_ip       = string
                network_tier = string
              }))
              ipv6_access_config = list(object({
                network_tier = string
              }))
              alias_ip_range = list(object({
                ip_cidr_range         = string
                subnetwork_range_name = string
              }))
            }))
        defaultValue: []
        connections:
          - source:
              source: github.com/singhalbhaskar/terraform-google-gke-cluster
              version: ">= 0.0.1"
            spec:
              outputExpr: additional_networks
  requirements:
    roles:
      - level: Project
        roles:
          - roles/owner
    services:
      - cloudresourcemanager.googleapis.com
      - storage-api.googleapis.com
      - serviceusage.googleapis.com
    providerVersions:
      - source: hashicorp/google
        version: ">= 4.83.0, < 7"
      - source: hashicorp/google-beta
        version: ">= 4.83.0, < 7"
